### ISSUE TITLE
Fix overlapping/crossing buildings 🏛 🏠 🏘 🏙 [maproulette]

### ISSUE THREAD

**Issue by maning** [OSMPH/papercut_fix#43]
_Continuing from https://github.com/OSMPH/papercut_fix/issues/13._
_Update: new workflow._

![screen shot 2018-03-30 at 09 16 58](https://user-images.githubusercontent.com/353700/38123847-2402a78c-33fb-11e8-9365-d9bd8e3bbf61.png)

*10K overlapping/crossing buildings as of March, 2018*

Using [OSMLint](https://github.com/osmlab/osmlint), we found 10K overlapping buildings in the Philippines. 😱  I created a maproulette task to fix this.  We need everyone to help!

1. Go to: http://maproulette.org/mr3/challenge/2992/
2. Grab a task. ![crossing-building](https://user-images.githubusercontent.com/353700/38411498-d35cb1e2-39a4-11e8-9549-3da8a88930d3.gif)
3. Select all buildings.  Click **Validation** (`Shift + V`).
4. Fix all crossing/overlapping building detected by the validator.
5. Changeset comment: `Fixed crossing/overlapping buildings. https://github.com/OSMPH/papercut_fix/issues/43`. Changeset source: `OSMLint; Maproulette` 

**Status**

|Date|N (% change)|Tasks (% change) | ⏹ (1k items) 
|---|---|----|---|
|2018-03-24|10,513 | 3,560 | ⏹⏹⏹⏹⏹⏹⏹⏹⏹⏹|
|2018-05-06| 7,672 (-25.34 %)| 3,299 (-7.33%) |⏹ ⏹⏹⏹⏹⏹⏹⏹|
|2018-05-28| 7,619 (-0.69 %)|3,209 (-2.73%)  |⏹⏹⏹⏹⏹⏹⏹⏹|

**Comment by govvin** [comment]
Deja vu?

![image](https://user-images.githubusercontent.com/5821688/38125331-39912752-341b-11e8-9a3a-49ba833106e2.png)

**Comment by schadow1** [comment]
![image](https://user-images.githubusercontent.com/6179495/38127392-88be798a-3428-11e8-9225-17dbac44980e.png)
Not Deja Vu @govvin Over 2.2 million buildings were mapped during the NOAH initiative back in 2016-2017 which comprises over 400% of the number of pre-existing buildings during that time. So it's probable and not surprising many of the overlapped buildings (17k or  .075% of the buildings mapped) were mapped during the initiative.
What I seem to not understand is how many times this was brought up on 2 opened issues over the 1 year period by you when it is already understandable where most of the issues came about, as per the number of updates made. I somewhat sometimes misconstrued this is a fault-finding task instead of a "fix".
The priority of the project was to map buildings so that they can be intersected with hazard maps. _Executive decisions and politics_ within the project during its course has limited the capacity of its manpower for thorough validations. Hence, as a respect to the people in the project, I am letting them have their say on this matter. I however do not know if they have already made a statement (publicly or privately) and what the statement was.
I however believe (based on my personal monitoring) that a few people from NOAH has already assisted in fixing a small part of the 7k of the overlapped buildings in the past year. I however still could not comprehend why the source of the issue is brought up many times and what is the point.

**Comment by govvin** [comment]
"Fix" is the correct term. The issue is quality assurance, as it has been in the original ticket. The facts - just like the numbers you quoted, also show how these happened.  These are not in dispute here.

It's been 10 months since these issues has been discovered, and partially fixed, but we don't see any more efforts from NOAH to complete this. The concern now is how to direct the limited resources of this community to clean up after this.

Thank you @schadow1 ,  for finally coming out to say what I surmise was the case, "limited capacity of its manpower for **thorough** validations."

>  Not Deja Vu @govvin Over 2.2 million buildings were mapped during the NOAH initiative back in 2016-2017 which comprises over 400% of the number of pre-existing buildings during that time. So it's probable and not surprising "many" of the overlapped buildings (31k or 1.3% of the buildings mapped) were mapped during the initiative.
What I seem to not understand is how many times this was brought up on 2 opened issues over the 1 year period by you when it is already understandable where most of the issues came about, as per the number of updates made. I somewhat sometimes misconstrued this is a fault-finding task instead of a "fix".
The priority of the project was to map buildings so that they can be intersected with hazard maps. Executive decisions and politics within the project during its course has limited the capacity of its manpower for thorough validations. Hence, as a respect to the people in the project, I am letting them have their say on this matter. I however do not know if they have already made a statement (publicly or privately) and what the statement was.
I however believe (based on my personal monitoring) that a few people from NOAH has already assisted in fixing a small part of the 7k of the overlapped buildings in the past year. I however still could not comprehend why the source of the issue is brought up many times and what is the point.

**Comment by maning** [comment]
🛑 The ticket is not intended to put blame on anyone.  Please use this ticket to coordinate the fixing effort.

**Comment by maning** [comment]
_Grid-based fixing instead of feature based (request for comments)._

**Whenever I fix an item, I always ran JOSM validator and fix adjacent overlapping/crossing buildings within my downloaded area.  I propose we adopt this approach instead of a feature-based fixing.**

Here's how it looks like in QGIS.
![screen shot 2018-04-06 at 06 09 29](https://user-images.githubusercontent.com/353700/38398508-df228a62-3961-11e8-9f30-ab8d3c661194.png)
*z16 grid over MultiPoint detection*

**For a z16 grid (~600 x 600 meters), we have 3560 grids to cover the 10K crossing errors.**  This approach will significantly reduce items in our challenge and reflects the approach to fixing I (and perhaps others) do.  

**Pros**
* less items to review in maproulette
* allows fixing all other crossing buildings within the downloaded area, instead of a single fix

**Cons**
* requires fixing in JOSM (+ validator)
* mapper cannot see the actual geometry to fix in maproulette

**Next actions**

* If 👍 , create a new challenge using grid-based fixing.
* If 👎 , ignore this comment and continue with current workflow.

**Comment by maning** [comment]
![screen shot 2018-04-06 at 14 19 09](https://user-images.githubusercontent.com/353700/38411786-7dcc6ae6-39a5-11e8-9dd0-e2f89acacc64.png)
Thanks! Updated OP for the new workflow and challenge URL.

**Comment by maning** [comment]
Sorry, but I have to delete buildings traced like in this task: http://maproulette.org/mr3/challenge/2992/task/4659337

![screen shot 2018-04-10 at 05 45 15](https://user-images.githubusercontent.com/353700/38529638-b7ee2dc8-3c83-11e8-947c-ec4405bad426.png)

![screen shot 2018-04-10 at 05 58 01](https://user-images.githubusercontent.com/353700/38529697-279b6212-3c84-11e8-8ddc-f0d75e890e34.png)

**Comment by feyeandal** [comment]
Hello! As we all know, the Catholic Relief Services (CRS) is currently implementing Project SUCCESS (Strengthening Urban Communities' Capacity to Endure Severe Shocks), directly supporting nine towns and cities in Metro Manila, Bulacan, and Rizal. The project aims to strengthen the capacity of local government units and vulnerable communities and enhance their resilience to floods and earthquakes. One of their main activities is to assist these LGUs to develop their disaster exposure database to help them identify and map the different structures that may be affected by natural hazards, so that they can better prepare and respond to these events. Last February, we conducted training and mapathon events to these cities to collect map information of buildings and other key elements on the ground. CRS formed a validation team within their organization, as well as UP Department of Geography to validate the data from the mapathon activities. I will be coordinating with these teams to help us fix the overlapping building issues, especially in Rizal area.

**Comment by maning** [comment]
Running status

|Date|N|Change
|---|---|----|
|2018-03-24|10,513 | |
|2018-04-30| 7,848| -25.34 %|

**Comment by feyeandal** [comment]
Hello!

Update and FYI: CRS agreed to help in validating the overlapping and crossing buildings in the areas covered by their project (some parts of Rizal, Malabon, and Marilao). They requested to just use their HOT Tasking Manager projects for validation instead of using the Maproulette task. The validation activities from the CRS team will be lead by @jdcayetano and @MARINOD.

Thanks!

**Comment by maning** [comment]
> use their HOT Tasking Manager projects for validation instead of using the Maproulette task

Sounds good @feyeandal!  Can you link here the TM projects?

**Comment by govvin** [comment]
@feyeandal , what's the latest with the validation effort of your project with CRS? cc: @jdcayetano @marinod

We still have these https://osm.org/go/4zhNQGxSE?m= :

![image](https://user-images.githubusercontent.com/5821688/40761836-f648904e-64cf-11e8-81a7-5b7135cc7cef.png)

**Comment by feyeandal** [comment]
Hello @govvin, the CRS team's validation is still on-going. They are also partnered with UP Department of Geography to fix the overlapping and crossing buildings in the CRS project sites.

Here are the following task numbers:
Angono 4476
Cainta 4185
Taytay 4614
Marilao 4474
Malabon 4475

**Comment by jdcayetano** [comment]
Hello @govvin,

We are continuing our efforts until July/August so this might take some time as we don’t have enough validators.

Sent from iPhone

--
Janeen Kim Cayetano | GIS Analyst, Global Knowledge and Information Management (GKIM) | +63 917 8011 366<tel:+63%20917%208011%20366> | janeenkim.cayetano@crs.org<mailto:janeenkim.cayetano@crs.org> | Skype: jdcayetano | 2<x-apple-data-detectors://3>F CBCP Bldg., 470 Gen. Luna St. Intramuros, Manila | crs.org<http://www.crs.org/> | CRS Philippines<http://www.facebook.com/CatholicReliefServicesPhilippines>

On 31 May 2018, at 12:51 PM, Feye Andal <notifications@github.com<mailto:notifications@github.com>> wrote:


Hello @govvin<https://github.com/govvin>, the CRS team's validation is still on-going. They are also partnered with UP Department of Geography to fix the overlapping and crossing buildings in the CRS project sites.

Here are the following task numbers:
Angono 4476
Cainta 4185
Taytay 4614
Marilao 4474
Malabon 4475

**Comment by govvin** [comment]
@feyeandal @jdcayetano 

Thank you for the quick heads-up. We're also still waiting to see the public project page, along with the list of editors and validators.

**Comment by feyeandal** [comment]
Hello, sorry for getting back late.

Here are the list of Youth mappers for each project site:

**Taytay, Rizal**
AdlerBBEMNHS
Jz_Mzlng
nomadiko
Joshua Abello
EdjinJerney
YvesTDM
ShadowPillow
markyc50
jang2x8
Elay Canaria
Arleane Cariso
Daniel Dave
Abe Lavarez
MISMNHS Efjay
MISMNHS Davey
MISMNHS Kathy
MISMNHS Krisha
MISMNHS Valerie
MISMNHS Regine
MISMNHS Christian
MISMNHS Ivan
MISMNHS Caila
MISMNHS Del

**Marilao, Bulacan**
SMSMSwin
JustArns
Ryanne0612
djjorge
Nicah Fatima
ReignYer
PNHSJMPQI
PNHSSRMP
PNHSCECI
PNHSMGS
PNHSMFG
PNHSLJSR
PNHSKCMG
PNHSCPM
PNHSJCP
PNHSRRC
PNHSSCVV
PNHSAAA
PNHSJJFJ

**Cainta, Rizal**
jiaisabel 
camille rose
Ernan joshua
buen23
peneyragresola

**Malabon**
Steeven14
camille mnlpz
CatherineFaith
Eman Santos
BarbstheGreat
jeremyyotch
EuniceCesniros13
ListraComia
ErynRae14
RheaMae
JulieAnne04
SophiaBianca
CieloJhane
FrenshieMae
ElaineBorja2004
YasmienNicolle
AngelRonquillo
JencellSahagun
AnaMarie03
Thund3rSt0rm
JeremiBuitizon
MarniVidal
MikaelaManuel
Krisna Angela Papa
Khriz Aldridge
LazaroChristelle
MarkClarenceAguilon
EmanuelJess
MichaelJay
RoviDeGuzman00
IVANJIMENEZ
DennisLacson01
StevenTarcena
HowardVelasco
EdrianVizmanos
NadineCanasta12

**Angono, Rizal**
ianaguinaldo
Laurence Royol
geronimo bulandra
bryanken

**Comment by govvin** [comment]
@feyeandal Thank you. 
In the future, please update this wiki page for updates regarding this project: https://wiki.openstreetmap.org/wiki/Project_SUCCESS

I took the list you posted earlier and added that as the initial entry for the page. Kindly add the other project details, when you can.

**Comment by maning** [comment]
Just visited the maproulette  challenge and it was now complete!

<img width="609" alt="Screenshot 2019-05-24 22 00 43" src="https://user-images.githubusercontent.com/353700/58333234-8e935280-7e6f-11e9-9532-f9f6d0ac177a.png">
