### ISSUE TITLE
remove extra string from feature names created by user

### ISSUE THREAD

**Issue by govvin** [OSMPH/papercut_fix#48]
A new [user](http://overpass-turbo.eu/s/ED7) has been adding " ®veoIII" to the name of the features they've been creating.

I left a comment in their most recent [changeset](https://www.openstreetmap.org/changeset/64183214), and waiting for their feedback.

Fix this if user doesn't respond a week from today

**Comment by govvin** [comment]
No response from user. 

Fixed by removing all instances and variations of the "veo" string in feature names edited by the user in the following changesets: 

* https://www.openstreetmap.org/changeset/65606689
* https://www.openstreetmap.org/changeset/65606159
* https://www.openstreetmap.org/changeset/65605930

**Comment by ianlopez1115** [comment]
Here we go again. [This](https://www.openstreetmap.org/changeset/71627301) was the most recent changeset, which was from 10 days ago while the earliest changeset since the initial cleanup was in [late January of the current year](https://www.openstreetmap.org/changeset/66649482#map=19/15.15262/120.59199). Should I go ahead and clean up names with the "veo" string?

**Comment by govvin** [comment]
@ianlopez1115 Thank you for the help @ianlopez1115 . Please do whatever's necessary.

**Comment by ianlopez1115** [comment]
@govvin Fixed, see https://www.openstreetmap.org/changeset/71953289 and https://www.openstreetmap.org/changeset/71953503

**Comment by govvin** [comment]
@ianlopez1115 Salamat ulit Ian! 👏

**Comment by ianlopez1115** [comment]
@govvin You're welcome
